### ISSUE TITLE
Graph in currently released version's README is broken

### ISSUE THREAD

**Issue by alexschrod** [jonhoo/evmap#14]
If you go to <https://crates.io/crates/evmap> and look at the bottom, there are broken images linking to files like <https://github.com/jonhoo/rust-evmap/raw/master/benchmark/read-throughput.png> which are not valid URLs.

**Comment by jonhoo** [comment]
This is because we're using relative links in the `README`, which won't resolve right on crates.io. But switching them to absolute URLs would mean that they wouldn't work for local development, in forks, or on branches. So I'd prefer to keep it as-is, even if that means the images won't show up on crates.io :)
